-- Gate 0 candidate schema (#74 §A/§B). Raw SQL on purpose: this runs against a
-- named scratch database before any Ecto migration is written, so the spike can
-- be thrown away without leaving migration history behind.
--
-- Only the parts the gate actually measures are here: the registry and its
-- exactly-one rule, the endpoint-compatibility FK, and the three
-- current-revision strategies side by side.

BEGIN;

-- ── the registry ────────────────────────────────────────────────────────────

CREATE TABLE objects (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind            text   NOT NULL,
  lifecycle_state text   NOT NULL DEFAULT 'active',
  inserted_at     timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT objects_kind CHECK (kind IN ('lexeme','sense','entity','content')),
  -- the handle every subtype's composite FK hangs off
  CONSTRAINT objects_id_kind UNIQUE (id, kind)
);

-- Kind is immutable. The composite FK below already blocks a change while a
-- subtype row exists; this covers the window before one is inserted, and gives
-- a readable error instead of a foreign-key violation.
CREATE FUNCTION objects_kind_is_immutable() RETURNS trigger AS $$
BEGIN
  IF NEW.kind IS DISTINCT FROM OLD.kind THEN
    RAISE EXCEPTION 'objects.kind is immutable (% -> %) for object %',
      OLD.kind, NEW.kind, OLD.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER objects_kind_immutable BEFORE UPDATE ON objects
  FOR EACH ROW EXECUTE FUNCTION objects_kind_is_immutable();

-- ── subtypes ────────────────────────────────────────────────────────────────
-- Each: object_id is the PRIMARY KEY (at most one row per object), and a
-- generated `kind` column carries the composite FK (that row is of the right
-- kind, and objects.kind cannot change underneath it).

CREATE TABLE lexemes (
  object_id       bigint PRIMARY KEY,
  kind            text GENERATED ALWAYS AS ('lexeme') STORED,
  language_tag    text NOT NULL DEFAULT 'en',
  lemma           text NOT NULL,
  part_of_speech  text NOT NULL DEFAULT 'unknown',
  lexical_key     text NOT NULL,
  slug            text NOT NULL,
  metadata        jsonb NOT NULL DEFAULT '{}',
  FOREIGN KEY (object_id, kind) REFERENCES objects (id, kind) ON DELETE CASCADE,
  CONSTRAINT lexemes_lexical_key UNIQUE (lexical_key)
);
CREATE INDEX lexemes_lower_lemma ON lexemes (lower(lemma));
CREATE INDEX lexemes_slug ON lexemes (slug);

CREATE TABLE entities (
  object_id       bigint PRIMARY KEY,
  kind            text GENERATED ALWAYS AS ('entity') STORED,
  entity_kind     text NOT NULL,
  preferred_label text,
  description     text,
  metadata        jsonb NOT NULL DEFAULT '{}',
  FOREIGN KEY (object_id, kind) REFERENCES objects (id, kind) ON DELETE CASCADE,
  CONSTRAINT entities_kind CHECK (entity_kind IN
    ('person','organization','concept','event','work','edition','place','artifact','taxon','other')),
  -- what person_details / work_details / edition_details hang their own
  -- composite FK off, so a subtype cannot attach to the wrong entity kind
  CONSTRAINT entities_object_id_entity_kind UNIQUE (object_id, entity_kind)
);

CREATE TABLE person_details (
  entity_id   bigint PRIMARY KEY,
  entity_kind text GENERATED ALWAYS AS ('person') STORED,
  birth_date  date,
  death_date  date,
  FOREIGN KEY (entity_id, entity_kind)
    REFERENCES entities (object_id, entity_kind) ON DELETE CASCADE
);

CREATE TABLE content_items (
  object_id         bigint PRIMARY KEY,
  kind              text GENERATED ALWAYS AS ('content') STORED,
  content_kind      text NOT NULL,
  original_language text,
  current_revision_id bigint,
  FOREIGN KEY (object_id, kind) REFERENCES objects (id, kind) ON DELETE CASCADE,
  CONSTRAINT content_items_kind CHECK (content_kind IN
    ('definition','article','quotation','passage','image','media','other'))
);

CREATE TABLE senses (
  object_id           bigint PRIMARY KEY,
  kind                text GENERATED ALWAYS AS ('sense') STORED,
  lexeme_id           bigint NOT NULL REFERENCES lexemes (object_id) ON DELETE CASCADE,
  source_slug         text   NOT NULL,
  external_key        text   NOT NULL,
  identity_state      text   NOT NULL DEFAULT 'active',
  current_revision_id bigint,
  FOREIGN KEY (object_id, kind) REFERENCES objects (id, kind) ON DELETE CASCADE,
  CONSTRAINT senses_identity_state CHECK (identity_state IN ('active','needs_review','retired')),
  CONSTRAINT senses_source_external UNIQUE (source_slug, external_key)
);
CREATE INDEX senses_lexeme ON senses (lexeme_id);

CREATE TABLE sense_revisions (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sense_id        bigint NOT NULL REFERENCES senses (object_id) ON DELETE CASCADE,
  revision_number int    NOT NULL,
  gloss           text,
  group_key       text,
  position        int    NOT NULL DEFAULT 0,   -- ordering only, never identity
  lifecycle_state text   NOT NULL DEFAULT 'active',
  CONSTRAINT sense_revisions_number UNIQUE (sense_id, revision_number),
  CONSTRAINT sense_revisions_sense_id_id UNIQUE (sense_id, id)
);

ALTER TABLE senses ADD CONSTRAINT senses_current_revision
  FOREIGN KEY (object_id, current_revision_id)
  REFERENCES sense_revisions (sense_id, id) DEFERRABLE INITIALLY DEFERRED;

-- ── exactly one subtype, checked at commit ──────────────────────────────────
-- The composite FKs above give "at most one, of the right kind". This gives the
-- other half. DEFERRABLE INITIALLY DEFERRED because the object row must exist
-- before the subtype row can reference it, so it is legitimately orphaned for
-- the length of the transaction.

CREATE FUNCTION object_has_subtype() RETURNS trigger AS $$
DECLARE
  found boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM lexemes       WHERE object_id = NEW.id UNION ALL
    SELECT 1 FROM senses        WHERE object_id = NEW.id UNION ALL
    SELECT 1 FROM entities      WHERE object_id = NEW.id UNION ALL
    SELECT 1 FROM content_items WHERE object_id = NEW.id
  ) INTO found;

  IF NOT found THEN
    RAISE EXCEPTION 'object % (kind %) has no % row', NEW.id, NEW.kind, NEW.kind
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER objects_require_subtype
  AFTER INSERT ON objects
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION object_has_subtype();

-- The other direction, and the one the first draft of this spike missed:
-- deleting a subtype row leaves the object behind, still referenced by every
-- assertion that named it. Measured on the first run — deleting Bierce's
-- entity row left object 101 (kind 'entity') with no entity, while
-- `authored_by` still pointed at it. An AFTER INSERT trigger on `objects`
-- cannot see that.
--
-- The check is skipped when the object is gone too, which is the ordinary
-- ON DELETE CASCADE path. The rule this leaves standing: an identity is
-- **retired** via objects.lifecycle_state, never deleted out from under the
-- claims that reference it.
CREATE FUNCTION subtype_delete_leaves_object_typed() RETURNS trigger AS $$
DECLARE
  still_there boolean;
  has_subtype boolean;
BEGIN
  SELECT EXISTS (SELECT 1 FROM objects WHERE id = OLD.object_id) INTO still_there;
  IF NOT still_there THEN
    RETURN NULL;                       -- the object went with it: fine
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM lexemes       WHERE object_id = OLD.object_id UNION ALL
    SELECT 1 FROM senses        WHERE object_id = OLD.object_id UNION ALL
    SELECT 1 FROM entities      WHERE object_id = OLD.object_id UNION ALL
    SELECT 1 FROM content_items WHERE object_id = OLD.object_id
  ) INTO has_subtype;

  IF NOT has_subtype THEN
    RAISE EXCEPTION 'object % would be left with no subtype row; retire it instead',
      OLD.object_id
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER lexemes_delete_keeps_object_typed
  AFTER DELETE ON lexemes DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION subtype_delete_leaves_object_typed();

CREATE CONSTRAINT TRIGGER senses_delete_keeps_object_typed
  AFTER DELETE ON senses DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION subtype_delete_leaves_object_typed();

CREATE CONSTRAINT TRIGGER entities_delete_keeps_object_typed
  AFTER DELETE ON entities DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION subtype_delete_leaves_object_typed();

CREATE CONSTRAINT TRIGGER content_items_delete_keeps_object_typed
  AFTER DELETE ON content_items DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION subtype_delete_leaves_object_typed();

-- ── predicates and their allowed endpoints ──────────────────────────────────

CREATE TABLE predicates (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key           text NOT NULL UNIQUE,
  forward_label text NOT NULL,
  reverse_label text NOT NULL,
  is_symmetric  boolean NOT NULL DEFAULT false,   -- SYMMETRIC is reserved in SQL
  is_transitive boolean NOT NULL DEFAULT false
);

-- Subkind is '-' rather than NULL when the kind has none: a foreign key with a
-- NULL column is not enforced under MATCH SIMPLE, which would silently disable
-- the whole check for every lexeme and sense endpoint.
CREATE TABLE predicate_endpoint_rules (
  predicate_id    bigint NOT NULL REFERENCES predicates (id) ON DELETE CASCADE,
  subject_kind    text   NOT NULL,
  subject_subkind text   NOT NULL DEFAULT '-',
  object_kind     text   NOT NULL,
  object_subkind  text   NOT NULL DEFAULT '-',
  PRIMARY KEY (predicate_id, subject_kind, subject_subkind, object_kind, object_subkind)
);

-- ── assertions ──────────────────────────────────────────────────────────────

CREATE TABLE assertions (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_slug         text,
  origin_key          text,
  current_revision_id bigint,
  CONSTRAINT assertions_origin UNIQUE (source_slug, origin_key)
);

CREATE TABLE assertion_revisions (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assertion_id      bigint NOT NULL REFERENCES assertions (id) ON DELETE CASCADE,
  revision_number   int    NOT NULL,
  subject_object_id bigint NOT NULL REFERENCES objects (id),
  predicate_id      bigint NOT NULL REFERENCES predicates (id),
  object_object_id  bigint NOT NULL REFERENCES objects (id),
  -- denormalised endpoint kinds, filled by the trigger below, so that
  -- compatibility is a real FK and therefore holds for insert_all and COPY
  subject_kind      text NOT NULL DEFAULT '-',
  subject_subkind   text NOT NULL DEFAULT '-',
  object_kind       text NOT NULL DEFAULT '-',
  object_subkind    text NOT NULL DEFAULT '-',
  method            text,
  confidence        double precision,
  lifecycle_state   text NOT NULL DEFAULT 'active',
  -- is_current is a THIRD strategy carried alongside the pointer purely so the
  -- benchmark can compare them on identical rows. Only one ships.
  is_current        boolean NOT NULL DEFAULT false,
  CONSTRAINT assertion_revisions_number UNIQUE (assertion_id, revision_number),
  CONSTRAINT assertion_revisions_assertion_id_id UNIQUE (assertion_id, id),
  CONSTRAINT assertion_revisions_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
  CONSTRAINT assertion_revisions_lifecycle CHECK (lifecycle_state IN ('active','withdrawn','superseded')),
  CONSTRAINT assertion_revisions_endpoints
    FOREIGN KEY (predicate_id, subject_kind, subject_subkind, object_kind, object_subkind)
    REFERENCES predicate_endpoint_rules (predicate_id, subject_kind, subject_subkind, object_kind, object_subkind)
);

ALTER TABLE assertions ADD CONSTRAINT assertions_current_revision
  FOREIGN KEY (id, current_revision_id)
  REFERENCES assertion_revisions (assertion_id, id) DEFERRABLE INITIALLY DEFERRED;

CREATE FUNCTION assertion_endpoint_kinds() RETURNS trigger AS $$
BEGIN
  SELECT o.kind,
         COALESCE(e.entity_kind, c.content_kind, '-')
    INTO NEW.subject_kind, NEW.subject_subkind
    FROM objects o
    LEFT JOIN entities e      ON e.object_id = o.id
    LEFT JOIN content_items c ON c.object_id = o.id
   WHERE o.id = NEW.subject_object_id;

  SELECT o.kind,
         COALESCE(e.entity_kind, c.content_kind, '-')
    INTO NEW.object_kind, NEW.object_subkind
    FROM objects o
    LEFT JOIN entities e      ON e.object_id = o.id
    LEFT JOIN content_items c ON c.object_id = o.id
   WHERE o.id = NEW.object_object_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER assertion_revisions_kinds BEFORE INSERT OR UPDATE ON assertion_revisions
  FOR EACH ROW EXECUTE FUNCTION assertion_endpoint_kinds();

COMMIT;
