-- Gate 0, proofs 4 and 5 (#74):
--   "Identical input creates zero new semantic revisions."
--   "Inserting/reordering/removing Wiktionary senses leaves attachments on the
--    original meaning or flags ambiguity; it never silently reassigns them."
--
-- The defect being fixed, from the 7 September audit: Wiktionary keys a sense
-- `word/pos/etymology_number#position`. Reordering the meanings overwrites the
-- row that "first meaning" pointed at with "second meaning", and every quote,
-- example and vote hanging off that id silently follows -- with no foreign key
-- violation anywhere, because the id is still valid. Parity reported zero gaps.
--
-- The policy proved here:
--   * `external_key` still records what the source called it, for provenance.
--     It is NOT identity.
--   * identity is matched on CONTENT: part of speech, etymology number, and the
--     normalised gloss, scored with pg_trgm.
--   * best match above @strong wins.
--   * a match above @weak but below @strong, or two candidates within @band of
--     each other, is AMBIGUOUS: the sense goes to needs_review and a
--     reconciliation case opens. It is never reassigned.
--   * an existing sense with no incoming match is RETIRED, not deleted, so the
--     attachments that reference it stay resolvable.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE reconciliation_cases (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_slug   text   NOT NULL,
  kind          text   NOT NULL,
  lexeme_id     bigint,
  sense_id      bigint,
  payload       jsonb  NOT NULL DEFAULT '{}',
  status        text   NOT NULL DEFAULT 'open',
  opened_at     timestamptz NOT NULL DEFAULT now()
);

-- Incoming senses, as an adapter would hand them over: source order included,
-- so the demonstration can reorder them.
-- `src_position` rather than `position`: PostgreSQL treats POSITION as a
-- reserved word in a RETURNS TABLE column list (it is the SQL string function),
-- so `RETURNS TABLE (position int, ...)` is a syntax error. Same class of
-- hazard as SYMMETRIC, which #74 already flagged. Found by running it.
CREATE TABLE incoming_senses (
  source_slug text,
  lexeme_id   bigint,
  src_position int,
  pos         text,
  etymology   int,
  gloss       text,
  external_key text
);

CREATE FUNCTION norm_gloss(t text) RETURNS text AS $$
  SELECT lower(regexp_replace(coalesce(t, ''), '[^a-z0-9 ]+', ' ', 'gi'));
$$ LANGUAGE sql IMMUTABLE;

-- Returns one row per incoming sense with the identity it resolved to and how.
CREATE FUNCTION reconcile(p_source text, p_lexeme bigint,
                          strong real DEFAULT 0.60, weak real DEFAULT 0.30, band real DEFAULT 0.08)
RETURNS TABLE (src_position int, decision text, matched_sense bigint, score real, runner_up real) AS $$
WITH existing AS (
  SELECT s.object_id,
         (s.external_key ~ '/[a-z]+/([0-9]+)') AS has_etym,
         split_part(s.external_key, '/', 2) AS pos,
         split_part(split_part(s.external_key, '/', 3), '#', 1) AS etym,
         norm_gloss(r.gloss) AS gloss
    FROM senses s
    JOIN sense_revisions r ON r.id = s.current_revision_id
   WHERE s.source_slug = p_source AND s.lexeme_id = p_lexeme
     AND s.identity_state = 'active'
),
scored AS (
  SELECT i.src_position,
         e.object_id,
         -- part of speech and etymology must agree at all; within that, the
         -- gloss decides. A source that renumbers etymologies is a separate
         -- reconciliation case and is not papered over here.
         CASE WHEN e.pos = i.pos AND e.etym = i.etymology::text
              THEN similarity(e.gloss, norm_gloss(i.gloss))
              ELSE 0 END AS score
    FROM incoming_senses i CROSS JOIN existing e
   WHERE i.source_slug = p_source AND i.lexeme_id = p_lexeme
),
ranked AS (
  SELECT src_position, object_id, score,
         row_number() OVER (PARTITION BY src_position ORDER BY score DESC, object_id) AS rn,
         lead(score) OVER (PARTITION BY src_position ORDER BY score DESC, object_id) AS next_score
    FROM scored
)
SELECT r.src_position,
       CASE
         WHEN r.score >= strong AND (r.next_score IS NULL OR r.score - r.next_score >= band)
           THEN 'matched'
         WHEN r.score >= weak THEN 'ambiguous'
         ELSE 'new'
       END,
       CASE WHEN r.score >= weak THEN r.object_id END,
       r.score,
       r.next_score
  FROM ranked r WHERE r.rn = 1
$$ LANGUAGE sql STABLE;
