defmodule DevilsDictionary.Routing.LaunchManifest do
  @moduledoc """
  The launch manifest the application reads (#237, ADR 0004 §7): the pages
  approved for publication, by page id and locale, each with its canonical
  path and the reviewer who approved it, and the On pages listed as
  indexable lexical entries (D1). Generated by the owner's standing review
  rule from a backfill run's candidate manifest, never written by hand
  (`priv/routing/launch-manifest.json`); its SHA-256 — of the file's bytes —
  is on every publication receipt made from it.

      {"format": "dd.launch-manifest/1",
       "from": {"file": …, "sha256": …, "run_key": …},
       "rule": {"sha256": …, "signer": …},
       "entries": [
         {"kind": "subject", "page_id": 1, "object_id": 1, "locale": "en",
          "path": "/people/ambrose-bierce", "family": "people",
          "reviewer": "…", "clause": "standing_decision", "evidence_fingerprint": "…"},
         {"kind": "lexical", "locale": "en", "path": "/on/bierce",
          "lexeme_ids": […], "subject_page_ids": [1], "reviewer": "…", "clause": "index_lexical"}],
       "deferred": [{"object_id": …, "clause": …, "reason": …}]}

  `read/1` checks the shape and needs no database; `validate/2` checks every
  page entry against the ledger and the accounts: the page exists in that
  role and locale, holds a canonical, the entry's path is that canonical,
  and its reviewer is a reviewer account (the rule's signer, under a rule).
  An empty manifest reads, publishes nothing, and says so.

  ## Generated by the rule

  `generate/3` makes one from a backfill run's candidate manifest (what
  `mix dd.routing.backfill --manifest` wrote), the population that run was
  bound to, and the signed standing review rule. `derive/3`, its pure part,
  builds each record's state from the backfill manifest and the population —
  its current decision, the address its page holds, the review a human made
  in that run — and asks `ReviewRule.decide/2`: every record the rule
  confirms at an address its page already holds is a page entry, reviewed by
  the rule's signer under the clause that confirmed it; one it confirms that
  has no address yet is `pending` (a backfill run under the rule allocates it
  first); everything else is listed under `deferred`, with the clause and the
  reason, visible and blocking nothing. Then, from the corpus, the lexical
  entries of D1 (`index_lexical`): the On page of each English lexeme one of
  whose senses `refers_to` a confirmed subject, through an asserted, public
  link. `generate/3` refuses inputs that are not bound to each other, and a
  result `validate/2` does not accept.
  """

  import Ecto.Query

  alias DevilsDictionary.Accounts.User
  alias DevilsDictionary.{Encyclopedia, Repo}
  alias DevilsDictionary.Routing.{Address, AuditSnapshot, Page, PublicPath, ReviewRule}

  @format "dd.launch-manifest/1"
  @page_kinds ~w(subject edition)
  @kinds @page_kinds ++ ~w(lexical)

  def format, do: @format

  @doc """
  Reads a launch manifest. Returns `{:ok, manifest}` with `:sha256` (the
  file's), `:rule_sha256` (or nil), `:entries`, `:pages` (the page entries
  by page id) and `:lexical`, or `{:error, message}`.
  """
  def read(path) do
    with {:ok, bytes} <- file(path),
         {:ok, doc} <- json(path, bytes),
         :ok <- shape(path, doc) do
      {:ok, from_doc(doc, AuditSnapshot.digest(bytes), path)}
    end
  end

  @doc "A manifest from its decoded document and its digest."
  def from_doc(doc, sha256, path \\ nil) do
    entries = doc["entries"]

    %{
      path: path,
      doc: doc,
      sha256: sha256,
      rule_sha256: get_in(doc, ["rule", "sha256"]),
      signer: get_in(doc, ["rule", "signer"]),
      entries: entries,
      pages: for(e <- entries, e["kind"] in @page_kinds, into: %{}, do: {e["page_id"], e}),
      lexical: Enum.filter(entries, &(&1["kind"] == "lexical"))
    }
  end

  defp file(path) do
    case File.read(path) do
      {:ok, bytes} -> {:ok, bytes}
      {:error, reason} -> {:error, "cannot read #{path}: #{:file.format_error(reason)}"}
    end
  end

  defp json(path, bytes) do
    case Jason.decode(bytes) do
      {:ok, %{} = doc} -> {:ok, doc}
      _ -> {:error, "launch manifest #{path}: not a JSON object"}
    end
  end

  defp shape(path, doc) do
    entries = doc["entries"]

    cond do
      doc["format"] != @format ->
        {:error, "launch manifest #{path}: format #{inspect(doc["format"])}, not #{@format}"}

      not is_list(entries) ->
        {:error, "launch manifest #{path}: entries is a list"}

      not (is_nil(doc["rule"]) or
               (is_map(doc["rule"]) and sha256?(doc["rule"]["sha256"]) and
                  is_binary(doc["rule"]["signer"]))) ->
        {:error, "launch manifest #{path}: a rule names its sha256 and its signer"}

      bad = Enum.find_value(entries, &entry_problem/1) ->
        {:error, "launch manifest #{path}: #{bad}"}

      (twice = duplicates(entries, & &1["page_id"], &(&1["kind"] in @page_kinds))) != [] ->
        {:error, "launch manifest #{path}: page #{hd(twice)} is listed twice"}

      (twice = duplicates(entries, &String.normalize(&1["path"], :nfc))) != [] ->
        {:error, "launch manifest #{path}: #{hd(twice)} is listed twice"}

      true ->
        :ok
    end
  end

  defp entry_problem(%{"kind" => kind, "path" => path} = entry)
       when kind in @kinds and is_binary(path) do
    parsed = Address.parse(path)

    cond do
      entry["locale"] != "en" ->
        "#{path}: locale #{inspect(entry["locale"])}; the launch locale is en"

      not (is_binary(entry["reviewer"]) and String.trim(entry["reviewer"]) != "") ->
        "#{path}: an entry names the reviewer who approved it"

      not match?({:ok, %{locale: "en"}}, parsed) ->
        "#{path} is not an address"

      kind == "lexical" and elem(parsed, 1).namespace != "on" ->
        "#{path}: a lexical entry is an On page"

      kind in @page_kinds and not (is_integer(entry["page_id"]) and entry["page_id"] > 0) ->
        "#{path}: a #{kind} entry names its page id"

      kind == "edition" and elem(parsed, 1).namespace != "works" ->
        "#{path}: an edition's address is in /works"

      kind == "subject" and elem(parsed, 1).namespace not in Address.families() ->
        "#{path}: a subject's address is in a family"

      true ->
        nil
    end
  end

  defp entry_problem(entry), do: "not an entry: #{inspect(entry)}"

  defp duplicates(entries, key, filter \\ fn _ -> true end) do
    entries
    |> Enum.filter(filter)
    |> Enum.frequencies_by(key)
    |> Enum.filter(fn {_key, n} -> n > 1 end)
    |> Enum.map(&elem(&1, 0))
    |> Enum.sort()
  end

  defp sha256?(value), do: is_binary(value) and value =~ ~r/\A[0-9a-f]{64}\z/

  @doc """
  Checks every page entry against the ledger and the accounts. Returns `:ok`
  or `{:error, problems}`, one line per entry that does not hold: no such
  page, a page of another role or locale, no canonical, a path that is not
  the page's canonical, a reviewer who is not a reviewer account, or — under
  a rule (`rule:`, a loaded `Routing.ReviewRule`) — a reviewer other than its
  signer or a manifest made under another rule.
  """
  def validate(manifest, opts \\ []) do
    rule = opts[:rule]
    ids = Map.keys(manifest.pages)

    pages =
      from(p in Page,
        left_join: c in PublicPath,
        on: c.id == p.canonical_path_id,
        where: p.id in ^ids,
        select: {p.id, {p, c}}
      )
      |> Repo.all()
      |> Map.new()

    reviewers =
      manifest.entries
      |> Enum.map(& &1["reviewer"])
      |> Enum.uniq()
      |> Map.new(&{&1, Repo.get_by(User, email: &1)})

    rule_problems =
      cond do
        is_nil(manifest.rule_sha256) ->
          []

        is_nil(rule) ->
          ["the manifest was made under rule #{manifest.rule_sha256}; load it"]

        rule.sha256 != manifest.rule_sha256 ->
          ["the manifest was made under rule #{manifest.rule_sha256}, not #{rule.sha256}"]

        true ->
          []
      end

    entry_problems =
      Enum.flat_map(manifest.entries, fn entry ->
        reviewer = reviewers[entry["reviewer"]]

        reviewer_problem =
          cond do
            not match?(%User{reviewer: true}, reviewer) ->
              ["#{entry["path"]}: #{entry["reviewer"]} is not a reviewer account"]

            rule && entry["reviewer"] != rule.signer.email ->
              ["#{entry["path"]}: approved by #{entry["reviewer"]}, not the rule's signer"]

            true ->
              []
          end

        reviewer_problem ++ page_problem(entry, pages)
      end)

    case rule_problems ++ entry_problems ++ binding_problems(manifest) do
      [] -> :ok
      problems -> {:error, problems}
    end
  end

  @doc """
  Whether a manifest that names a standing review rule is the rule's: every
  page entry is an `allocated` item of the backfill run the manifest names
  (`from.run_key`), for that object and that page, and the lexical entries
  are exactly what the rule's query derives from the corpus for those
  pages. A manifest that names no rule is not the rule's to check. Returns
  `:ok` or `{:error, problems}`; `mix dd.routing.publish` publishes nothing
  under a rule unless it holds, because the rule's signature is the
  publication authority and the owner's rule is that a manifest is never
  written by hand (#237).
  """
  def bound_to_rule(manifest) do
    case binding_problems(manifest) do
      [] -> :ok
      problems -> {:error, problems}
    end
  end

  defp binding_problems(%{rule_sha256: nil}), do: []

  defp binding_problems(%{doc: doc} = manifest) do
    run_key = get_in(doc, ["from", "run_key"])
    pages = Enum.filter(manifest.entries, &(&1["kind"] in @page_kinds))

    allocated =
      if is_binary(run_key) do
        Repo.all(
          from i in "routing_backfill_items",
            join: r in "routing_backfill_runs",
            on: r.id == i.run_id,
            where: r.run_key == ^run_key and i.disposition == "allocated",
            select: {i.object_id, i.page_id}
        )
        |> MapSet.new()
      else
        MapSet.new()
      end

    page_problems =
      cond do
        not is_binary(run_key) ->
          ["the manifest names a rule but no backfill run (from.run_key)"]

        MapSet.size(allocated) == 0 ->
          ["run #{run_key} allocated nothing in this database"]

        true ->
          for e <- pages, not MapSet.member?(allocated, {e["object_id"], e["page_id"]}) do
            "#{e["path"]}: page #{e["page_id"]} of object #{e["object_id"]} is not an allocation of run #{run_key}"
          end
      end

    signer = manifest.signer || get_in(doc, ["rule", "signer"])

    derived =
      pages
      |> lexical_entries(signer)
      |> Enum.map(&lexical_key/1)
      |> Enum.sort()

    given = manifest.lexical |> Enum.map(&lexical_key/1) |> Enum.sort()

    lexical_problems =
      if derived == given,
        do: [],
        else: [
          "the lexical entries are not the rule's: #{length(given)} given, #{length(derived)} derived " <>
            "from the corpus for these pages (#{length(given -- derived)} not derived, " <>
            "#{length(derived -- given)} missing)"
        ]

    page_problems ++ lexical_problems
  end

  defp lexical_key(entry) do
    entry = Map.new(entry)

    {entry["path"], Enum.sort(entry["lexeme_ids"] || []),
     Enum.sort(entry["subject_page_ids"] || [])}
  end

  defp page_problem(%{"kind" => "lexical"}, _pages), do: []

  defp page_problem(%{"page_id" => id, "kind" => kind, "path" => path}, pages) do
    case pages[id] do
      nil ->
        ["#{path}: no page #{id}"]

      {page, canonical} ->
        cond do
          Atom.to_string(page.role) != kind ->
            ["#{path}: page #{id} is a #{page.role} page, not a #{kind} page"]

          page.locale != "en" ->
            ["#{path}: page #{id} is in locale #{page.locale}"]

          is_nil(canonical) ->
            ["#{path}: page #{id} has no canonical"]

          canonical.path != String.normalize(path, :nfc) ->
            ["#{path}: page #{id}'s canonical is #{canonical.path}"]

          true ->
            []
        end
    end
  end

  # ── generating ───────────────────────────────────────────────────────────

  @confirming ~w(uncontested_mapping qualified_collision)

  @doc """
  The launch manifest the standing rule makes from a backfill manifest:
  reads `from_path` and `population_path`, checks that the backfill manifest
  was made from that population and that its run is this database's, derives
  the entries (`derive/3`), adds the lexical entries, and checks the result
  against the ledger. `rule` is the loaded, signed rule. Returns `{:ok, doc}`
  (an ordered document, ready to write) or `{:error, message}`. Reads only.
  """
  def generate(from_path, population_path, rule) do
    with {:ok, from_bytes} <- file(from_path),
         {:ok, from} <- json(from_path, from_bytes),
         {:ok, population_bytes} <- file(population_path),
         {:ok, population} <- json(population_path, population_bytes),
         from = %{
           doc: from,
           sha256: AuditSnapshot.digest(from_bytes),
           file: Path.basename(from_path)
         },
         population = %{doc: population, sha256: AuditSnapshot.digest(population_bytes)},
         :ok <- bound(from, population),
         :ok <- same_run(from.doc),
         derived = derive(from, population, %{sha256: rule.sha256, signer: rule.signer.email}),
         lexical = lexical_entries(derived.entries, rule.signer.email),
         doc = document(from, population, rule, derived, lexical),
         manifest = from_doc(Jason.decode!(Jason.encode!(doc)), "generated"),
         :ok <- valid(validate(manifest, rule: rule)) do
      {:ok, doc}
    end
  end

  defp bound(from, population) do
    named = get_in(from.doc, ["inputs", "population_sha256"])

    cond do
      not is_list(from.doc["records"]) or not is_binary(from.doc["run_key"]) ->
        {:error, "#{from.file} is not a backfill manifest (run_key, records)"}

      named != population.sha256 ->
        {:error,
         "#{from.file} was made from population #{inspect(named)}, not #{population.sha256}"}

      true ->
        :ok
    end
  end

  # The backfill manifest describes a run in this database: the same records,
  # dispositions and pages as its checkpoint.
  defp same_run(backfill) do
    run_key = backfill["run_key"]

    rows =
      Repo.all(
        from i in "routing_backfill_items",
          join: r in "routing_backfill_runs",
          on: r.id == i.run_id,
          where: r.run_key == ^run_key,
          select: {i.object_id, i.disposition, i.page_id}
      )

    expected =
      Enum.map(backfill["records"], &{&1["object_id"], &1["disposition"], &1["page_id"]})

    cond do
      rows == [] ->
        {:error, "run #{run_key} is not in this database"}

      Enum.sort(rows) != Enum.sort(expected) ->
        {:error, "the backfill manifest does not match run #{run_key}'s checkpoint"}

      true ->
        :ok
    end
  end

  defp valid(:ok), do: :ok

  defp valid({:error, problems}),
    do: {:error, "the generated manifest does not hold:\n  " <> Enum.join(problems, "\n  ")}

  @doc """
  The rule's entries for a backfill manifest, without a database: `from` and
  `population` are `%{doc:, sha256:}` (and `from.file`), `rule` is
  `%{sha256:, signer:}`. Returns `%{entries:, pending:, deferred:, counts:}`.
  """
  def derive(from, population, rule) do
    records = Map.new(population.doc["records"], &{&1["object_id"], &1})

    group_of =
      for {path, ids} <- population.doc["groups"] || %{}, id <- ids, into: %{}, do: {id, path}

    under_rule = get_in(from.doc, ["inputs", "rule_sha256"])
    reviews? = is_binary(get_in(from.doc, ["inputs", "reviews_sha256"]))

    states =
      for item <- from.doc["records"] do
        id = item["object_id"]

        %{
          object_id: id,
          label: records[id]["label"],
          role: if(item["page_role"] == "edition", do: :edition, else: :subject),
          population: Map.put(records[id] || %{}, "group", group_of[id]),
          entity: nil,
          decision: decision(item, under_rule),
          canonical: item["address"],
          earlier_review: earlier(item, reviews? and is_nil(under_rule)),
          stale: nil
        }
      end

    held =
      for item <- from.doc["records"], is_binary(item["address"]), into: %{} do
        {String.normalize(item["address"], :nfc), item["object_id"]}
      end

    decisions = ReviewRule.decide(states, held)
    items = Map.new(from.doc["records"], &{&1["object_id"], &1})

    {entries, rest} =
      decisions
      |> Enum.sort()
      |> Enum.split_with(fn {id, d} ->
        d.action == :confirm and d.standing and is_integer(items[id]["page_id"])
      end)

    entries =
      for {id, d} <- entries do
        item = items[id]

        Jason.OrderedObject.new([
          {"kind", item["page_role"] || "subject"},
          {"page_id", item["page_id"]},
          {"object_id", id},
          {"locale", "en"},
          {"path", d.path},
          {"family", d.family},
          {"reviewer", rule.signer},
          # The clause that confirmed it: a run under the rule names it on
          # its checkpoint (`rule_clause`); an address kept from a human's
          # review is the rule's standing_decision.
          {"clause", confirming_clause(item) || d.clause},
          {"evidence_fingerprint", d.fingerprint}
        ])
      end

    {pending, deferred} = Enum.split_with(rest, fn {_id, d} -> d.action == :confirm end)

    %{
      entries: entries,
      pending:
        for(
          {id, d} <- pending,
          do:
            Jason.OrderedObject.new(
              object_id: id,
              clause: d.clause,
              family: d.family,
              path: d.path
            )
        ),
      deferred:
        for(
          {id, d} <- deferred,
          do:
            Jason.OrderedObject.new(
              object_id: id,
              action: Atom.to_string(d.action),
              clause: d.clause,
              reason: d.reason
            )
        ),
      counts: decisions |> Map.values() |> Enum.frequencies_by(&"#{&1.action} #{&1.clause}")
    }
  end

  defp confirming_clause(%{"rule_clause" => clause}) when clause in @confirming, do: clause
  defp confirming_clause(_item), do: nil

  defp decision(%{"status" => nil}, _under_rule), do: nil

  defp decision(item, under_rule) do
    %{
      status: item["status"],
      family: item["family"],
      origin: item["decided_by"],
      fingerprint: item["evidence_fingerprint"],
      reasons: [],
      # An override the rule wrote in that run names the rule; any other is
      # a reviewer's own.
      rule_sha256:
        if(item["decided_by"] == "override" and item["rule_clause"] in @confirming,
          do: under_rule
        )
    }
  end

  # What a reviewer decided in that run, when a review file decided it.
  defp earlier(%{"disposition" => "deferred_by_review"} = item, true),
    do: %{"action" => "defer", "reason" => item["reason"]}

  defp earlier(%{"disposition" => "allocated"}, true), do: %{"action" => "confirm"}
  defp earlier(_item, _reviews?), do: nil

  # D1: the On page of each English lexeme a sense of which `refers_to` a
  # confirmed subject through an asserted, public link; one entry per slug.
  defp lexical_entries([], _signer), do: []

  defp lexical_entries(entries, signer) do
    pages = Map.new(entries, &{&1["object_id"], &1["page_id"]})

    %{rows: rows} =
      Repo.query!(
        """
        SELECT DISTINCT lx.object_id, lx.slug, r.object_object_id
          FROM assertion_revisions r
          JOIN predicates p ON p.id = r.predicate_id AND p.key = 'refers_to'
          JOIN senses s ON s.object_id = r.subject_object_id
          JOIN lexemes lx ON lx.object_id = s.lexeme_id AND lx.language_tag = 'en'
         WHERE r.is_current AND r.lifecycle_state = 'active'
           AND r.object_object_id = ANY($1)
           AND (r.confidence IS NULL OR r.confidence >= $2)
           AND COALESCE(
                 (SELECT ar.decision FROM assertion_reviews ar
                   WHERE ar.assertion_revision_id = r.id
                   ORDER BY ar.inserted_at DESC, ar.id DESC LIMIT 1),
                 'needs_review') NOT IN ('rejected', 'withdrawn')
        """,
        [Map.keys(pages), Encyclopedia.asserted_floor()]
      )

    rows
    |> Enum.filter(fn [_lexeme, slug, _subject] -> is_binary(slug) and on_path?(slug) end)
    |> Enum.group_by(fn [_lexeme, slug, _subject] -> slug end)
    |> Enum.sort()
    |> Enum.map(fn {slug, links} ->
      Jason.OrderedObject.new([
        {"kind", "lexical"},
        {"locale", "en"},
        {"path", "/on/" <> slug},
        {"lexeme_ids", links |> Enum.map(&Enum.at(&1, 0)) |> Enum.uniq() |> Enum.sort()},
        {"subject_page_ids",
         links |> Enum.map(&pages[Enum.at(&1, 2)]) |> Enum.uniq() |> Enum.sort()},
        {"reviewer", signer},
        {"clause", "index_lexical"}
      ])
    end)
  end

  defp on_path?(slug), do: match?({:ok, %{namespace: "on"}}, Address.parse("/on/" <> slug))

  defp document(from, population, rule, derived, lexical) do
    Jason.OrderedObject.new([
      {"format", @format},
      {"issue", "https://github.com/razrfly/dictionary/issues/237"},
      {"generated_by",
       "mix dd.routing.publish --rule priv/routing/review-rule.json --from #{from.file} --write-manifest"},
      {"from",
       Jason.OrderedObject.new([
         {"file", from.file},
         {"sha256", from.sha256},
         {"run_key", from.doc["run_key"]},
         {"inputs", from.doc["inputs"]}
       ])},
      {"population", Jason.OrderedObject.new([{"sha256", population.sha256}])},
      {"rule",
       Jason.OrderedObject.new([
         {"sha256", rule.sha256},
         {"signer", rule.signer.email},
         {"signed_at", rule.signature["signed_at"]}
       ])},
      {"counts",
       Jason.OrderedObject.new([
         {"pages", length(derived.entries)},
         {"lexical", length(lexical)},
         {"pending", length(derived.pending)},
         {"deferred", length(derived.deferred)},
         {"by_clause", derived.counts |> Enum.sort() |> Jason.OrderedObject.new()}
       ])},
      {"entries", derived.entries ++ lexical},
      {"pending", derived.pending},
      {"deferred", derived.deferred}
    ])
  end
end
