defmodule DevilsDictionary.Routing.LaunchManifest do
  @moduledoc """
  The launch manifest the application reads (#237, ADR 0004 §7): the pages
  approved for publication, by page id and locale, each with its canonical
  path and the reviewer who approved it, and the On pages listed as
  indexable lexical entries (D1). Generated by the owner's standing review
  rule from a backfill run's candidate manifest, never written by hand
  (`priv/routing/launch-manifest.json`); its SHA-256 — of the file's bytes —
  is on every publication receipt made from it.

      {"format": "dd.launch-manifest/1",
       "from": {"file": …, "sha256": …, "run_key": …},
       "rule": {"sha256": …, "signer": …},
       "entries": [
         {"kind": "subject", "page_id": 1, "object_id": 1, "locale": "en",
          "path": "/people/ambrose-bierce", "family": "people",
          "reviewer": "…", "clause": "standing_decision", "evidence_fingerprint": "…"},
         {"kind": "lexical", "locale": "en", "path": "/on/bierce",
          "lexeme_ids": […], "subject_page_ids": [1], "reviewer": "…", "clause": "index_lexical"}],
       "deferred": [{"object_id": …, "clause": …, "reason": …}]}

  `read/1` checks the shape and needs no database; `validate/2` checks every
  page entry against the ledger and the accounts: the page exists in that
  role and locale, holds a canonical, the entry's path is that canonical,
  and its reviewer is a reviewer account (the rule's signer, under a rule).
  An empty manifest reads, publishes nothing, and says so.
  """

  import Ecto.Query

  alias DevilsDictionary.Accounts.User
  alias DevilsDictionary.Repo
  alias DevilsDictionary.Routing.{Address, AuditSnapshot, Page, PublicPath}

  @format "dd.launch-manifest/1"
  @page_kinds ~w(subject edition)
  @kinds @page_kinds ++ ~w(lexical)

  def format, do: @format

  @doc """
  Reads a launch manifest. Returns `{:ok, manifest}` with `:sha256` (the
  file's), `:rule_sha256` (or nil), `:entries`, `:pages` (the page entries
  by page id) and `:lexical`, or `{:error, message}`.
  """
  def read(path) do
    with {:ok, bytes} <- file(path),
         {:ok, doc} <- json(path, bytes),
         :ok <- shape(path, doc) do
      {:ok, from_doc(doc, AuditSnapshot.digest(bytes), path)}
    end
  end

  @doc "A manifest from its decoded document and its digest."
  def from_doc(doc, sha256, path \\ nil) do
    entries = doc["entries"]

    %{
      path: path,
      doc: doc,
      sha256: sha256,
      rule_sha256: get_in(doc, ["rule", "sha256"]),
      signer: get_in(doc, ["rule", "signer"]),
      entries: entries,
      pages: for(e <- entries, e["kind"] in @page_kinds, into: %{}, do: {e["page_id"], e}),
      lexical: Enum.filter(entries, &(&1["kind"] == "lexical"))
    }
  end

  defp file(path) do
    case File.read(path) do
      {:ok, bytes} -> {:ok, bytes}
      {:error, reason} -> {:error, "cannot read #{path}: #{:file.format_error(reason)}"}
    end
  end

  defp json(path, bytes) do
    case Jason.decode(bytes) do
      {:ok, %{} = doc} -> {:ok, doc}
      _ -> {:error, "launch manifest #{path}: not a JSON object"}
    end
  end

  defp shape(path, doc) do
    entries = doc["entries"]

    cond do
      doc["format"] != @format ->
        {:error, "launch manifest #{path}: format #{inspect(doc["format"])}, not #{@format}"}

      not is_list(entries) ->
        {:error, "launch manifest #{path}: entries is a list"}

      not (is_nil(doc["rule"]) or
               (is_map(doc["rule"]) and sha256?(doc["rule"]["sha256"]) and
                  is_binary(doc["rule"]["signer"]))) ->
        {:error, "launch manifest #{path}: a rule names its sha256 and its signer"}

      bad = Enum.find_value(entries, &entry_problem/1) ->
        {:error, "launch manifest #{path}: #{bad}"}

      (twice = duplicates(entries, & &1["page_id"], &(&1["kind"] in @page_kinds))) != [] ->
        {:error, "launch manifest #{path}: page #{hd(twice)} is listed twice"}

      (twice = duplicates(entries, &String.normalize(&1["path"], :nfc))) != [] ->
        {:error, "launch manifest #{path}: #{hd(twice)} is listed twice"}

      true ->
        :ok
    end
  end

  defp entry_problem(%{"kind" => kind, "path" => path} = entry)
       when kind in @kinds and is_binary(path) do
    parsed = Address.parse(path)

    cond do
      entry["locale"] != "en" ->
        "#{path}: locale #{inspect(entry["locale"])}; the launch locale is en"

      not (is_binary(entry["reviewer"]) and String.trim(entry["reviewer"]) != "") ->
        "#{path}: an entry names the reviewer who approved it"

      not match?({:ok, %{locale: "en"}}, parsed) ->
        "#{path} is not an address"

      kind == "lexical" and elem(parsed, 1).namespace != "on" ->
        "#{path}: a lexical entry is an On page"

      kind in @page_kinds and not (is_integer(entry["page_id"]) and entry["page_id"] > 0) ->
        "#{path}: a #{kind} entry names its page id"

      kind == "edition" and elem(parsed, 1).namespace != "works" ->
        "#{path}: an edition's address is in /works"

      kind == "subject" and elem(parsed, 1).namespace not in Address.families() ->
        "#{path}: a subject's address is in a family"

      true ->
        nil
    end
  end

  defp entry_problem(entry), do: "not an entry: #{inspect(entry)}"

  defp duplicates(entries, key, filter \\ fn _ -> true end) do
    entries
    |> Enum.filter(filter)
    |> Enum.frequencies_by(key)
    |> Enum.filter(fn {_key, n} -> n > 1 end)
    |> Enum.map(&elem(&1, 0))
    |> Enum.sort()
  end

  defp sha256?(value), do: is_binary(value) and value =~ ~r/\A[0-9a-f]{64}\z/

  @doc """
  Checks every page entry against the ledger and the accounts. Returns `:ok`
  or `{:error, problems}`, one line per entry that does not hold: no such
  page, a page of another role or locale, no canonical, a path that is not
  the page's canonical, a reviewer who is not a reviewer account, or — under
  a rule (`rule:`, a loaded `Routing.ReviewRule`) — a reviewer other than its
  signer or a manifest made under another rule.
  """
  def validate(manifest, opts \\ []) do
    rule = opts[:rule]
    ids = Map.keys(manifest.pages)

    pages =
      from(p in Page,
        left_join: c in PublicPath,
        on: c.id == p.canonical_path_id,
        where: p.id in ^ids,
        select: {p.id, {p, c}}
      )
      |> Repo.all()
      |> Map.new()

    reviewers =
      manifest.entries
      |> Enum.map(& &1["reviewer"])
      |> Enum.uniq()
      |> Map.new(&{&1, Repo.get_by(User, email: &1)})

    rule_problems =
      cond do
        is_nil(manifest.rule_sha256) ->
          []

        is_nil(rule) ->
          ["the manifest was made under rule #{manifest.rule_sha256}; load it"]

        rule.sha256 != manifest.rule_sha256 ->
          ["the manifest was made under rule #{manifest.rule_sha256}, not #{rule.sha256}"]

        true ->
          []
      end

    entry_problems =
      Enum.flat_map(manifest.entries, fn entry ->
        reviewer = reviewers[entry["reviewer"]]

        reviewer_problem =
          cond do
            not match?(%User{reviewer: true}, reviewer) ->
              ["#{entry["path"]}: #{entry["reviewer"]} is not a reviewer account"]

            rule && entry["reviewer"] != rule.signer.email ->
              ["#{entry["path"]}: approved by #{entry["reviewer"]}, not the rule's signer"]

            true ->
              []
          end

        reviewer_problem ++ page_problem(entry, pages)
      end)

    case rule_problems ++ entry_problems do
      [] -> :ok
      problems -> {:error, problems}
    end
  end

  defp page_problem(%{"kind" => "lexical"}, _pages), do: []

  defp page_problem(%{"page_id" => id, "kind" => kind, "path" => path}, pages) do
    case pages[id] do
      nil ->
        ["#{path}: no page #{id}"]

      {page, canonical} ->
        cond do
          Atom.to_string(page.role) != kind ->
            ["#{path}: page #{id} is a #{page.role} page, not a #{kind} page"]

          page.locale != "en" ->
            ["#{path}: page #{id} is in locale #{page.locale}"]

          is_nil(canonical) ->
            ["#{path}: page #{id} has no canonical"]

          canonical.path != String.normalize(path, :nfc) ->
            ["#{path}: page #{id}'s canonical is #{canonical.path}"]

          true ->
            []
        end
    end
  end
end
