import Config

# Configure your database
config :devils_dictionary, DevilsDictionary.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "devils_dictionary_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :devils_dictionary, DevilsDictionaryWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ECxygwHtDn8OFiRoCbhB5kvtsT2Np1WVR2ThlLPyIJZ7OrXGk/1pkbwum9lmyGF4",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:devils_dictionary, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:devils_dictionary, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :devils_dictionary, dev_routes: true

# Absorbs run millions of statements; Ecto logs each one at :debug, which buries
# the numbers a task prints. Raise the floor to :info and pass `--log-level debug`
# style opts only when actually debugging a query.
config :logger, level: :info

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
