import Config

# Configure your database
config :devils_dictionary, DevilsDictionary.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  # #74: the encyclopedia model is built in a NEW database. `devils_dictionary_dev`
  # is left intact -- nothing is destroyed, and it stays available as the matched
  # baseline for the Gate 0 benchmarks and P5's semantic comparison. It is
  # reachable only through the two scripts that need it, never from app code.
  database: "devils_dictionary_v2",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :devils_dictionary, DevilsDictionaryWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Port 4007: 4000–4005 belong to the sibling projects in this directory.
  http: [ip: {127, 0, 0, 1}, port: 4007],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ECxygwHtDn8OFiRoCbhB5kvtsT2Np1WVR2ThlLPyIJZ7OrXGk/1pkbwum9lmyGF4",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:devils_dictionary, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:devils_dictionary, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :devils_dictionary, dev_routes: true

# Fake-data mode (#71 §2.8, U3). `?demo=1` does nothing at all unless this is
# set, and it is set here and in `test.exs` only: `prod.exs` and `runtime.exs`
# never mention the key, which is the same gate `dev_routes` uses for `/kit`.
# `demo_inert_test.exs` reads `prod.exs` back and fails if it ever grows one.
config :devils_dictionary, demo_mode: true

# Absorbs run millions of statements; Ecto logs each one at :debug, which buries
# the numbers a task prints. Raise the floor to :info and pass `--log-level debug`
# style opts only when actually debugging a query.
config :logger, level: :info

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
