import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :devils_dictionary, DevilsDictionaryWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :devils_dictionary, DevilsDictionaryWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Public subject addresses stay off in production (#237 D5): the published
# host is the owner's development server, enabled in `config/runtime.exs`'s
# development block only. `PublicRoutingTest` holds this pin.
config :devils_dictionary, :public_routing, false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
